version: '3'
services:
    web.nginx:
        image: nginx:latest
        container_name: "web.nginx"
        ports:
            - "80:80"
            - "3000:443"
        restart: always
        volumes:
            - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/ssl:/etc/ssl"
            - "./web/stats-digital/:/web/stats-digital"
        links:
            - php 
            - mongo
        depends_on:
            - php
            - mongo
    php:
        build: ./panda-php-stack
        container_name: "php"
        restart: always
        working_dir: /web/stats-digital
        volumes:
#            - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - ./web/stats-digital:/web/stats-digital
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo
        container_name: "mongo"
        restart: always
        volumes:
            - ./data/db/mongo:/data/db
        ports:
            - "27020:27017"
        command: --storageEngine wiredTiger
